# ------------------------------------
# GutHub Action 
#
# Copyleft (c) by Roman Goryachev 2021
#-------------------------------------

name: Testing-Dual-Illusion
env:
  APPLICATION_NAME: 'MY-Illision'
  PACKAGE_NAME    : 'My-Illision-version-${{ github.sha }}'
  
# Controls when the action will run. 
on:
  push:
    branches: 
      - master
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_work: 
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
    - name: Print Hello from Work
      run: echo "Hello Roman Work flow"
      
    - name: Execure few commands
      run: |
        echo "Hello Message 1"
        echo "Hello Message 2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
        
   
      
  my_testing:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello from Testing
      run: echo "Hello Roman Testing flow"

  
    
  my_deploy: 
    runs-on: ubuntu-latest
    needs: [my_work]
    
    steps:
    - name: Print Hello from Deploy
      run: echo "Hello Roman Deploy flow"
      
    - name: Deployment packages 
      run : |
        echo "Deployment packages: ${{ env.PACKAGE_NAME }}"
        
    - name: Lets test some packages if the are here 1
      run: aws --version
      
    - name: Lets test some packages if the are here 1
      run: zip --version 
      
    
   
   
   
   
   
   
   
   
   
   
 
        
        
